logging:
  level:
    root: WARN
    org.example.quotes: TRACE
server:
  port: 8085
  servlet:
    context-path: /api/v1
spring:
  h2:
    console:
      settings:
        web-allow-others: true
        trace: false
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:quotes_db
    username: sa
    password:
  jpa:
    open-in-view: false
    show-sql: true
  flyway:
    enabled: true
    clean-disabled: false
springdoc:
  api-docs:
    path: /api-docs
rsa:
  priv: classpath:cert/private_key.pem
  pub: classpath:cert/public_key.pem
